
 function [BW,maskedRGBImage]= createMask(RGB1)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder app. The colorspace and
%  range for each channel of the colorspace were set within the app. The
%  segmentation mask is returned in BW, and a composite of the mask and
%  original RGB images is returned in maskedRGBImage.

% Auto-generated by colorThresholder app on 28-Aug-2019
%------------------------------------------------------
% Convert RGB image to chosen color space
I = rgb2lab(RGB1);

% Define thresholds for channel 1 based on histogram settings
channel1Min = 0.020;
channel1Max = 11.659;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 0.139;
channel2Max = 45.349;

% Define thresholds for channel 3 based on histogram settings
channel3Min = -19.801;
channel3Max = -0.378;

% Create mask based on chosen histogram thresholds
sliderBW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);
BW = sliderBW;

% Initialize output masked image based on input image.
maskedRGBImage = RGB1;

% Set background pixels where BW is false to zero.
maskedRGBImage(repmat(~BW,[1 1 3])) = 0;

end
